server:
  port: 8002


spring:
  application:
    name: cloud-entity-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.93.129:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dbuser
    password: DBuser@123_!@#

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.uyun.entity

logging:
  level:
    com.uyun: debug


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true
